MyPortfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from MyPortfolio import views

urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('portfolio/', include('PortfolioDatabase.urls')),
]

PortfolioDatabase/urls.py
from django.urls import path

from PortfolioDatabase import views

app_name = 'PortfolioDatabase'


urlpatterns = [
    path('', views.home, name="home"),
    path('hobbies/', views.hobbies, name="hobbies"),
    path('projects/', views.projects, name="projects"),
    path('contact/', views.contact, name="contact"),
    path('hobbies/<int:hobby_id>', views.hobby, name="hobby"),
    path('projects/<int:project_id>', views.project, name="project"),
]

PortfolioDatabase/models.py
from django.db import models


class Hobby(models.Model):

    def __str__(self):
        return self.hobby_name

    hobby_name = models.CharField(max_length=200)
    hobby_description = models.CharField(max_length=200)
    skill_level = models.IntegerField()
    hobby_image = models.CharField(max_length=2000, default='https://clipart-library.com/img/48366.jpg')


class Project(models.Model):

    def __str__(self):
        return self.project_name

    project_name = models.CharField(max_length=200)
    project_description = models.CharField(max_length=200)
    project_link = models.CharField(max_length=300)
    project_image = models.CharField(max_length=2000, default='https://www.pngitem.com/pimgs/m/302-3024031_projects-icon-png-skills-icon-for-resume-png.png')

MyPortfolio/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("please navigate to /portfolio")

PortfolioDatabase/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render

from .models import Hobby, Project


def home(request):
    return render(request, "home.html")


def contact(request):
    return render(request, "contact.html")


def hobbies(request):
    context = {}
    context["dataset"] = Hobby.objects.all()
    return render(request, "hobbies.html", context)


def hobby(request, hobby_id):
    context = {}
    context["dataset"] = Hobby.objects.get(pk=hobby_id)
    return render(request, "hobby.html", context)


def projects(request):
    context = {}
    context["dataset"] = Project.objects.all()
    return render(request, "projects.html", context)


def project(request, project_id):
    context = {}
    context["dataset"] = Project.objects.get(pk=project_id)
    return render(request, "project.html", context)

PortfolioDatabase/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Portfolio</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "PortfolioDatabase/style.css" %}">
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">Elijah Cannon</a>
        <div class="navbar">
            <a href="{% url 'PortfolioDatabase:home' %}" class="nav-item nav-link" style="color: #fff">Home</a>
            <a href="{% url 'PortfolioDatabase:hobbies' %}" class="nav-item nav-link" style="color: #fff">Hobbies</a>
            <a href="{% url 'PortfolioDatabase:projects' %}" class="nav-item nav-link" style="color: #fff">Projects</a>
            <a href="{% url 'PortfolioDatabase:contact' %}" class="nav-item nav-link" style="color: #fff">Contact</a>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

PortfolioDatabase/templates/contact.html
{% extends 'base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Portfolio : Contact Me</title>
</head>
<body>
    {% block body %}
    <div class="container">
        <h1 style="margin: 50px 0">Contact Me</h1>
        <p>Email: elijahcannon@mail.weber.edu</p>
    </div>
    {% endblock %}
</body>
</html>

PortfolioDatabase/templates/hobbies.html
{% extends 'base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Portfolio : hobbies</title>
</head>
<body>
{% block body %}
    <div class="container">
        <h1 style="margin: 50px 0">My Hobbies</h1>
        {% for data in dataset %}
        <div class="row">
            <div class="col-md-3">
                <img src="{{ data.hobby_image }}" alt="hobby" height="100px">
            </div>
            <div class="col-md-6">
                <h4>{{ data.hobby_name }}</h4>
                <p>Skill level: {{ data.skill_level }}</p>
            </div>
            <div class="col-md-2" style="display:flex;align-items:center">
                <a href="{% url 'PortfolioDatabase:hobby' data.id %}" class="btn btn-success">Details</a>
            </div>
        </div>
        <hr/>
        {% endfor %}
    </div>
{% endblock %}
</body>
</html>

PortfolioDatabase/templates/hobby.html
{% extends 'base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Hobbies</title>
</head>
<body>
{% block body %}
    <div class="container">
        <h1 style="margin: 50px 0">{{ dataset.hobby_name }}</h1>
        <div class="row" style="margin-bottom: 50px;">
            <div style="margin-right: 50px; margin-bottom: 50px;">
                <img src="{{ dataset.hobby_image }}" alt="hobby" height="200px">
            </div>
            <div style="flex:1">
                <h4>Skill level: {{ dataset.skill_level }}</h4>
                <h6>{{ dataset.hobby_description }}</h6>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

PortfolioDatabase/templates/home.html
{% extends 'base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Portfolio</title>
</head>
<body>
{% block body %}
<div class="container">
    <h1 style="margin: 50px 0">Home</h1>
    <p>Welcome to my rocking portfolio &#128640;</p>
    <p>My name is Elijah Cannon and I am a senior at Weber State University studying computer science :) Please check out my hobbies and also the cool projects I have been working on.</p>

</div>
{% endblock %}
</body>
</html>

PortfolioDatabase/templates/project.html
{% extends 'base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Projects</title>
</head>
<body>
{% block body %}
    <div class="container">
        <h1 style="margin: 50px 0">{{dataset.project_name}}</h1>
        <div class="row" style="margin-bottom: 50px;">
            <div class="">
                <img src="{{ dataset.project_image }}" alt="project" height="200px" style="margin-bottom: 50px;margin-right: 50px;">
            </div>
            <div class="" style="flex:1">
                <p>{{ dataset.project_description }}</p>
                {% if dataset.project_link != 'n/a' %}
                <a href="https://{{ dataset.project_link }}" target="_blank" class="btn btn-primary">Check it out</a>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}
</body>
</html>

PortfolioDatabase/templates/projects.html
{% extends 'base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Portfolio : Projects</title>
</head>
<body>
{% block body %}
    <div class="container">
        <h1 style="margin: 50px 0">My Projects</h1>
        {% for data in dataset %}
        <div class="row">
            <div class="col-md-3">
                <img src="{{ data.project_image }}" alt="project" height="100px">
            </div>
            <div class="col-md-6">
                <h4>{{ data.project_name }}</h4>
                <p>{{data.project_description}}</p>
            </div>
            <div class="col-md-3" style="display:flex;align-items:center; justify-content:flex-end">
                <a href="{% url 'PortfolioDatabase:project' data.id %}" class="btn btn-success">Details</a>
            </div>
        </div>
        <hr/>
        {% endfor %}
    </div>
{% endblock %}
</body>
</html>